# Generated by Django 5.2 on 2025-05-05 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='is_wholesale',
        ),
        migrations.AddField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
