# Generated by Django 5.2 on 2025-05-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_deal_date_remove_deal_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
