# Generated by Django 5.2 on 2025-05-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_deal_created_at_deal_date_deal_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата сделки'),
        ),
        migrations.AlterField(
            model_name='dealitem',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.deal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='DealProduct',
        ),
    ]
